In [26]:
import numpy as np
from transformers import AutoTokenizer
from tqdm import tqdm

In [39]:
data_path_1 = '/home/abishekthamma/PycharmProjects/masters_thesis/ss-llm/nanoGPT/data/babylm_full_bpe_8k_test'
data_path_2 = '/home/abishekthamma/PycharmProjects/masters_thesis/ss-llm/nanoGPT/data/babylm_full_bpe_8k'

td = "train.bin"
vd = "val.bin"

data_1 = np.memmap(data_path_1 + '/' + td, dtype=np.uint16, mode='r')
data_2 = np.memmap(data_path_2 + '/' + td, dtype=np.uint16, mode='r')

print(data_1.shape, data_2.shape)

tokenizer_1 = AutoTokenizer.from_pretrained(data_path_1)
tokenizer_2 = AutoTokenizer.from_pretrained(data_path_2)


(14545183,) (14545185,)


In [40]:
tk = 0
for i, j in tqdm(enumerate(data_1)):
    k = i+tk
    if data_1[i] != data_2[k]:
        tk+=1
        print(i, data_1[i], data_2[k])
        if i > 100:
            print(data_1[i-5:i+5], "\n", data_2[k-5:k+5])
            print(tokenizer_1.decode(data_1[i-5:i+5]), "\n  \n \n", tokenizer_2.decode(data_2[k-5:k+5]))
            
    

5900931it [00:07, 835228.35it/s]

5769336 1400 997
[ 319   12  358  476  311 1400  208  710  478  196] 
 [ 319   12  358  476  311  997 1400  208  710  478]
 know, she said solike you'd say to 
  
 
  know, she said so    like you'd say


14545183it [00:17, 826571.85it/s]

14383913 47 133
[ 274  203  173 1332   14   47  444  173  597  513] 
 [ 274  203  173 1332   14  133   47  444  173  597]
 do in the morning.i think the only people 
  
 
  do in the morning. i think the only
